"""Add Payment and more other models

Revision ID: 11e4ba22534b
Revises: 8209a4ae9882
Create Date: 2026-03-04 20:09:16.902098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e4ba22534b'
down_revision = '8209a4ae9882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_shipment_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_billing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_promotions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_shipment_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_billing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_promotions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('account_name')
        batch_op.drop_column('paypal_email')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('description')
        batch_op.drop_column('account_number')
        batch_op.drop_column('paypal_link')
        batch_op.drop_column('qr_code_url')
        batch_op.drop_column('sort_code')
        batch_op.drop_column('swift_code')
        batch_op.drop_column('network')
        batch_op.drop_column('wallet_address')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('swift_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sort_code', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('qr_code_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('paypal_link', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('paypal_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('config')
        batch_op.drop_column('method_type')

    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('push_enabled')
        batch_op.drop_column('app_security')
        batch_op.drop_column('app_promotions')
        batch_op.drop_column('app_billing')
        batch_op.drop_column('app_shipment_updates')
        batch_op.drop_column('email_security')
        batch_op.drop_column('email_promotions')
        batch_op.drop_column('email_billing')
        batch_op.drop_column('email_shipment_updates')

    # ### end Alembic commands ###
