"""models updated

Revision ID: 2017f8401bba
Revises: 
Create Date: 2026-02-28 19:50:15.934253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2017f8401bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receiver_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('receiver_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.alter_column('dimensions',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('dimensions',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('cost')
        batch_op.drop_column('receiver_company')
        batch_op.drop_column('receiver_phone')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
