"""user models updated

Revision ID: 244709f6d538
Revises: ffb70e0eb2f3
Create Date: 2026-03-01 01:10:45.982431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244709f6d538'
down_revision = 'ffb70e0eb2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
