"""working on subscription

Revision ID: 37dfd2e25398
Revises: 244709f6d538
Create Date: 2026-03-01 02:04:15.627166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37dfd2e25398'
down_revision = '244709f6d538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notif', sa.Boolean(), nullable=True),
    sa.Column('notif_booking', sa.Boolean(), nullable=True),
    sa.Column('notif_status', sa.Boolean(), nullable=True),
    sa.Column('notif_otd', sa.Boolean(), nullable=True),
    sa.Column('notif_delivered', sa.Boolean(), nullable=True),
    sa.Column('notif_delays', sa.Boolean(), nullable=True),
    sa.Column('notif_news', sa.Boolean(), nullable=True),
    sa.Column('sms_notif', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_fa_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_fa_secret')
        batch_op.drop_column('two_fa_enabled')
        batch_op.drop_column('avatar_url')

    op.drop_table('notification_preference')
    # ### end Alembic commands ###
