"""add is_ai_chat to live_chat_session

Revision ID: 5324db7cea99
Revises: d97919532ea7
Create Date: 2026-03-06 21:53:24.771709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5324db7cea99'
down_revision = 'd97919532ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_chat', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.drop_column('is_ai_chat')

    # ### end Alembic commands ###
