"""Add Payment and more other  models

Revision ID: 8209a4ae9882
Revises: 8af0dc91c19b
Create Date: 2026-03-04 18:26:42.176218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8209a4ae9882'
down_revision = '8af0dc91c19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('account_name')
        batch_op.drop_column('sort_code')
        batch_op.drop_column('paypal_email')
        batch_op.drop_column('wallet_address')
        batch_op.drop_column('qr_code_url')
        batch_op.drop_column('network')
        batch_op.drop_column('paypal_link')
        batch_op.drop_column('swift_code')
        batch_op.drop_column('description')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('swift_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('paypal_link', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('network', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('qr_code_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('wallet_address', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('paypal_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('sort_code', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('config')
        batch_op.drop_column('method_type')

    # ### end Alembic commands ###
