"""add is_ai to live_chat_messages

Revision ID: bfacb46eba67
Revises: 98608ba693de
Create Date: 2026-03-07 14:28:14.027623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfacb46eba67'
down_revision = '98608ba693de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.Boolean(), nullable=True))

    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###
