"""working on notification

Revision ID: cb7a184678c3
Revises: f684c1cdefb2
Create Date: 2026-03-02 13:39:22.254489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7a184678c3'
down_revision = 'f684c1cdefb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('related_shipment_id', sa.Integer(), nullable=True),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['support_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_shipment_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_billing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_promotions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_shipment_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_billing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_promotions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('app_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('push_enabled')
        batch_op.drop_column('app_security')
        batch_op.drop_column('app_promotions')
        batch_op.drop_column('app_billing')
        batch_op.drop_column('app_shipment_updates')
        batch_op.drop_column('email_security')
        batch_op.drop_column('email_promotions')
        batch_op.drop_column('email_billing')
        batch_op.drop_column('email_shipment_updates')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    # ### end Alembic commands ###
