"""add is_ai to live_chat_messages

Revision ID: 98608ba693de
Revises: 5324db7cea99
Create Date: 2026-03-07 14:26:02.254056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98608ba693de'
down_revision = '5324db7cea99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_session', schema=None) as batch_op:
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###
