"""add new_message  to live_chat_messages

Revision ID: b6cb1e345dda
Revises: bfacb46eba67
Create Date: 2026-03-07 14:30:45.207677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cb1e345dda'
down_revision = 'bfacb46eba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.drop_column('new_message')

    # ### end Alembic commands ###
