"""Make config nullable

Revision ID: d97919532ea7
Revises: 11e4ba22534b
Create Date: 2026-03-04 21:43:18.361896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd97919532ea7'
down_revision = '11e4ba22534b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_payment_method')
    op.drop_table('_alembic_tmp_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('two_fa_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('two_fa_secret', sa.VARCHAR(length=32), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('_alembic_tmp_payment_method',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('method_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
