"""fixing payments requests

Revision ID: df9df02e3c8b
Revises: 0f3066dfb2a4
Create Date: 2026-03-02 00:06:42.301131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9df02e3c8b'
down_revision = '0f3066dfb2a4'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'payment_method' not in tables:
        op.create_table('payment_method',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('code', sa.String(length=20), nullable=False),
            sa.Column('display_name', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('icon', sa.String(length=50), nullable=True),
            sa.Column('wallet_address', sa.String(length=500), nullable=True),
            sa.Column('qr_code_url', sa.String(length=500), nullable=True),
            sa.Column('network', sa.String(length=50), nullable=True),
            sa.Column('bank_name', sa.String(length=100), nullable=True),
            sa.Column('account_number', sa.String(length=100), nullable=True),
            sa.Column('account_name', sa.String(length=100), nullable=True),
            sa.Column('routing_number', sa.String(length=50), nullable=True),
            sa.Column('swift_code', sa.String(length=50), nullable=True),
            sa.Column('paypal_email', sa.String(length=120), nullable=True),
            sa.Column('paypal_link', sa.String(length=500), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('code')
        )
    
    # Check if column exists before adding
    if 'payment_request' in tables:
        columns = [col['name'] for col in inspector.get_columns('payment_request')]
        if 'payment_method_id' not in columns:
            with op.batch_alter_table('payment_request', schema=None) as batch_op:
                batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key('fk_payment_request_payment_method', 'payment_method', ['payment_method_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_request_payment_method', type_='foreignkey')
        batch_op.drop_column('payment_method_id')

    op.drop_table('payment_method')
    # ### end Alembic commands ###
