"""deburging

Revision ID: e9be17dcb5b9
Revises: df9df02e3c8b
Create Date: 2026-03-02 02:13:18.026502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9be17dcb5b9'
down_revision = 'df9df02e3c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_code', sa.String(length=20), nullable=True))
        batch_op.drop_column('routing_number')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routing_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('sort_code')

    # ### end Alembic commands ###
