"""models updated again

Revision ID: ffb70e0eb2f3
Revises: 2017f8401bba
Create Date: 2026-03-01 00:53:39.602783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb70e0eb2f3'
down_revision = '2017f8401bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('renews_at', sa.DATETIME(), nullable=True),
    sa.Column('previous_plan_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('changed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
